language: python
dist: focal
cache:
  pip: true
  directories:
  - /home/travis/R/Library
  - /home/travis/.cache/ExperimentHub
env:
- R_LIBS_SITE=/home/travis/R/Library
branches:
  only:
  - master  # All other branches should become (draft) PRs and be build that way

# matrix
python:
- '3.6'
- '3.7'
- '3.8'

# packages
addons:
  apt:
    sources:
    - sourceline: 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
      key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE298A3A825C0D65DFD57CBB651716619E084DAB9'
    update: true
    packages:
    - r-base
# install basic requirements
before_install:
- sudo R --slave -e 'install.packages("BiocManager", repos="https://cloud.r-project.org/")'
- sudo R --slave -e 'options(warn = 2); BiocManager::install(c("SingleCellExperiment", "scRNAseq"))'
- mkdir -p ~/.cache/ExperimentHub
- pip install flit get_version 'rpy2<3.4' pygments
# install package
install:
- python -m rpy2.situation
- flit install --extras=all
# test
script:
- PYTHONPATH=. pytest
